# Generated by Django 4.1.9 on 2023-06-27 11:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [
        ("surveys", "0001_initial"),
        ("surveys", "0002_answer"),
        ("surveys", "0003_remove_survey_title_and_more"),
        ("surveys", "0004_remove_question_survey_question_survey"),
        ("surveys", "0005_question_name"),
        ("surveys", "0006_survey_name_survey_slug"),
        ("surveys", "0007_question_options"),
        ("surveys", "0008_remove_question_options_questiontranslation_options"),
        ("surveys", "0009_alter_question_question_type"),
        ("surveys", "0010_answer_created_at"),
        ("surveys", "0011_alter_question_options_alter_survey_options"),
        ("surveys", "0012_alter_survey_options"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="default", max_length=60)),
                ("slug", models.SlugField(default="def", max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("single_select", "Single Select"),
                            ("multiple_select", "Multiple Select"),
                            ("likert_5", "likert_5"),
                            ("likert_7", "likert_7"),
                            ("number", "number"),
                            ("prompt", "prompt"),
                        ],
                        max_length=60,
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "survey",
                    models.ManyToManyField(
                        related_name="questions", to="surveys.survey"
                    ),
                ),
                ("name", models.CharField(default="default", max_length=60)),
            ],
            options={"ordering": ["order"]},
        ),
        migrations.CreateModel(
            name="SurveyTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("es", "Spanish"), ("en", "English")], max_length=60
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="surveys.survey"
                    ),
                ),
                ("title", models.CharField(default="test", max_length=255)),
            ],
            options={"unique_together": {("survey", "language")}},
        ),
        migrations.CreateModel(
            name="QuestionTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("es", "Spanish"), ("en", "English")], max_length=60
                    ),
                ),
                ("question_prompt", models.TextField()),
                (
                    "survey_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveys.question",
                    ),
                ),
                ("options", models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={"unique_together": {("survey_question", "language")}},
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answers", models.JSONField(default=dict)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="surveys.survey"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, default=django.utils.timezone.now
                    ),
                ),
            ],
        ),
    ]
