# Generated by Django 4.1.9 on 2023-06-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("surveys", "0003_remove_survey_title_and_more")]

    operations = [
        migrations.RemoveField(model_name="question", name="survey"),
        migrations.AddField(
            model_name="question",
            name="survey",
            field=models.ManyToManyField(related_name="questions", to="surveys.survey"),
        ),
    ]
