# Generated by Django 4.1.9 on 2023-06-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_remove_question_survey_question_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='default', max_length=60),
            preserve_default=False,
        ),
    ]
