# Generated by Django 4.1.9 on 2023-06-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0008_remove_question_options_questiontranslation_options")
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("single_select", "Single Select"),
                    ("multiple_select", "Multiple Select"),
                    ("likert_5", "likert_5"),
                    ("likert_7", "likert_7"),
                    ("number", "number"),
                    ("prompt", "prompt"),
                ],
                max_length=60,
            ),
        )
    ]
