# Generated by Django 4.1.9 on 2023-06-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("surveys", "0010_answer_created_at")]

    operations = [
        migrations.AlterModelOptions(name="question", options={"ordering": ["order"]}),
        migrations.AlterModelOptions(
            name="survey", options={"ordering": ["questions__order"]}
        ),
    ]
