# Generated by Django 4.1.9 on 2023-06-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("surveys", "0011_alter_question_options_alter_survey_options")]

    operations = [migrations.AlterModelOptions(name="survey", options={})]
