# Generated by Django 4.1.9 on 2023-06-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("surveys", "0001_squashed_0012_alter_survey_options")]

    operations = [
        migrations.AddField(
            model_name="question",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="answer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="question", name="name", field=models.CharField(max_length=60)
        ),
        migrations.AlterField(
            model_name="survey", name="name", field=models.CharField(max_length=60)
        ),
        migrations.AlterField(
            model_name="survey",
            name="slug",
            field=models.SlugField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name="surveytranslation",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
