# Generated by Django 4.1.9 on 2023-08-01 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("surveys", "0014_alter_question_question_type_recording"),
        ("surveys", "0015_alter_recording_options_recording_language"),
    ]

    dependencies = [
        ("surveys", "0013_question_hidden_alter_answer_created_at_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("single_select", "Single Select"),
                    ("multiple_select", "Multiple Select"),
                    ("likert_5", "likert_5"),
                    ("likert_7", "likert_7"),
                    ("number", "number"),
                    ("prompt", "prompt"),
                    ("recording", "recording"),
                ],
                max_length=60,
            ),
        ),
        migrations.CreateModel(
            name="Recording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recording", models.FileField(upload_to="recordings/")),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="surveys.answer"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("es", "Spanish"), ("en", "English")],
                        default="en",
                        max_length=60,
                    ),
                ),
            ],
            options={"verbose_name": "Record", "verbose_name_plural": "Records"},
        ),
    ]
