# Generated by Django 4.1.9 on 2023-08-09 06:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "surveys",
            "0014_alter_question_question_type_recording_squashed_0015_alter_recording_options_recording_language",
        )
    ]

    operations = [
        migrations.AddField(
            model_name="recording",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="recording",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="surveys.answer",
            ),
        ),
        migrations.AlterField(
            model_name="recording",
            name="language",
            field=models.CharField(
                choices=[("es", "Spanish"), ("en", "English")], max_length=60
            ),
        ),
    ]
