# Generated by Django 4.1.9 on 2023-08-15 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("surveys", "0016_recording_uuid_alter_recording_answer_and_more")]

    operations = [
        migrations.CreateModel(
            name="Screen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screens",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="question",
            name="screen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="surveys.screen",
            ),
        ),
    ]
