# Generated by Django 4.1.9 on 2023-10-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("surveys", "0017_screen_question_screen")]

    operations = [
        migrations.AddField(
            model_name="question",
            name="exclusion_value",
            field=models.JSONField(blank=True, max_length=120, null=True),
        )
    ]
